### PR TITLE
Add new time format 'hours'

### PR DESCRIPTION
**Pull request by hirasso**
OK, my try at making #245 work. Main struggle was getting the thing to run. I had a few type errors when running `npm run compile:watch`, but got them resolved. Hope this was the help you where looking for :)

### CODE REVIEW

**Comment by fabiospampinato** [comment]
Can you rewrite this using a coding style that's more consistent with mine?

**Comment by fabiospampinato** [comment]
And did you manually test that this works as intended?

**Comment by hirasso** [comment]
> Can you rewrite this using a coding style that's more consistent with mine?

Sure, what exactly do you mean? Do you have a standards defined anywhere in your project?

> And did you manually test that this works as intended?

Yes, tested it manually, worked for me

**Comment by hirasso** [comment]
Actually, I didn't fix the type errors that where already in your code base. Posting them here for reference:
```
ERROR in /Users/rah/Nextcloud/vscode-todo-plus/src/todo/document.ts
./src/todo/document.ts
[tsl] ERROR in /Users/rah/Nextcloud/vscode-todo-plus/src/todo/document.ts(23,7)
      TS2322: Type 'string | TextDocument | TextEditor' is not assignable to type 'string'.
  Type 'TextDocument' is not assignable to type 'string'.

ERROR in /Users/rah/Nextcloud/vscode-todo-plus/src/todo/document.ts
./src/todo/document.ts
[tsl] ERROR in /Users/rah/Nextcloud/vscode-todo-plus/src/todo/document.ts(27,26)
      TS2361: The right-hand side of an 'in' expression must be of type 'any', an object type or a type parameter.

ERROR in /Users/rah/Nextcloud/vscode-todo-plus/src/utils/time.ts
./src/utils/time.ts
[tsl] ERROR in /Users/rah/Nextcloud/vscode-todo-plus/src/utils/time.ts(126,15)
      TS2339: Property 'replace' does not exist on type 'string | number'.
  Property 'replace' does not exist on type 'number'.

ERROR in /Users/rah/Nextcloud/vscode-todo-plus/src/utils/time.ts
./src/utils/time.ts
[tsl] ERROR in /Users/rah/Nextcloud/vscode-todo-plus/src/utils/time.ts(127,15)
      TS2339: Property 'replace' does not exist on type 'string | number | Date'.
  Property 'replace' does not exist on type 'number'.

ERROR in /Users/rah/Nextcloud/vscode-todo-plus/src/utils/time.ts
./src/utils/time.ts
[tsl] ERROR in /Users/rah/Nextcloud/vscode-todo-plus/src/utils/time.ts(129,33)
      TS2345: Argument of type 'string | number | Date' is not assignable to parameter of type 'string'.
  Type 'number' is not assignable to type 'string'.
```
...but it compiled nevertheless...

**Comment by hirasso** [comment]
Good morning :) I tried to make change my code's style to better fit yours (empty lines). Is this what you meant?

**Comment by fabiospampinato** [comment]
Partially, yes. You had forgotten to update `todo.timekeeping.elapsed.format` in `package.json`.

This is now available in v4.15.0, thanks!

**Pull request closed without merging**
