### PR TITLE
Refactor - Replace moment with date-fns

### LINKED ISSUE #248: Replace moment.js with date-fns
I think date-fns is now the more modern date library. Some reasons why it's preferable over moment.js: https://www.quora.com/What-is-better-Date-fns-or-moment-js. This is definitely not urgent, but it might be a nice dev experience upgrade to use a newer cleaner API.

As a side note: would you be open to switching to using an opinionated code formatter like prettier?

### PR DESCRIPTION
**Pull request by brkn**
closes #248 

Hi 👋🏻 
This pr replaces moment with date-fns.

Notes:
* Added some obvious typings, let me know if this is not okay.
* Date-fns package uses a different date formatting string. Please see here: https://git.io/fxCyr
* To not have breaking changes for this, I've just replaced these capital 'D' and 'Y'

### CODE REVIEW

**Comment by fabiospampinato** [comment]
- Why?
- Why not moment-mini?
- What numbers do you see improved (extension size, startup time...)
- Replacing Ds like that is not correct as not all uppercase Ds should be replaced. Plus `String.prototype.replace` doesn't work like that: `'DADDY'.replace("D", "d").replace("Y", "y");` => `dADDy`

**Comment by brkn** [comment]
> Why?

Wanted to contrribute on issue labelled as *help-wanted* on a project I've been using daily for a year. I am sorry I don't understand if what I am doing is wrong? Did I break an etiquette rule, please let me know.

> Why not moment-mini?

If I recall correctly moment is not great with the tree shaking and is kinda chunky with bundle size. It's also stopped being developed and the maintainers themselves suggest alternatives see [here](https://momentjs.com/docs/). `Moment-mini`is just zipped moment, not sure if it would be a better improvement.

> What numbers do you see improving (extension size, startup time...)?

* I compared the output size, please see next comment.
* I don't know how to benchmark startup time, can you point me how would I go with this?

> Replacing Ds like that is not correct as not all uppercase Ds should be replaced. Plus String.prototype.replace doesn't work like that: 'DADDY'.replace("D", "d").replace("Y", "y"); => dADDy

My bad. I will fix "the daddy issues :D" if you think it's good idea to continue with this.

**Comment by brkn** [comment]
###### Small side note 
* My local was not working right now with this package.json, it could be helpful to include a lock file.
* To fix it I've upgraded these:
  ```
  "@types/node": "^14.11.8",
  "typescript": "3.1",
  ```
* So the comparison below might not be very accurate.
###### Comparison of output size
* Basically it is ~%20 smaller in package size with date-fns.
* Run `webpack --mode production` with momentjs
  ```
  du -h out
  4.3M    out
  ```
  ```
  Built at: 10/15/2020 8:35:46 PM
             Asset      Size  Chunks                   Chunk Names
      extension.js   784 KiB       0  [emitted]        main
  extension.js.map  3.57 MiB       0  [emitted] [dev]  main
  Entrypoint main = extension.js extension.js.map
    [4] external "vscode" 42 bytes {0} [built]
    [6] ./src/consts.ts 5.75 KiB {0} [built]
    [9] ./src/config.ts 1.28 KiB {0} [built]
   [15] ./src/utils/index.ts 1.15 KiB {0} [built]
   [18] ./src/todo/items/item.ts 1.98 KiB {0} [built]
   [47] ./src/todo/document.ts 3.84 KiB {0} [built]
   [50] ./src/utils/folder.ts 2.21 KiB {0} [built]
   [62] ./src/views/embedded.ts 2.75 KiB {0} [built]
   [69] ./src/views/files.ts 2.88 KiB {0} [built]
   [82] ./src/utils/ast.ts 3.5 KiB {0} [built]
  [335] ./src/todo/decorators/document.ts 5.54 KiB {0} [built]
  [336] ./src/extension.ts 2.74 KiB {0} [built]
  [337] ./src/providers/completion.ts 1.4 KiB {0} [built]
  [854] ./src/providers/symbols.ts 1.82 KiB {0} [built]
  [862] ./src/todo/decorators/changes.ts 1010 bytes {0} [built]
      + 848 hidden modules
  ✨  Done in 23.02s.
  ```
* Run `webpack --mode production` with date-fns
  ```
  du -h out
  3.5M    out
  ```
  ```
  Built at: 10/15/2020 8:32:37 PM
             Asset      Size  Chunks                   Chunk Names
      extension.js   566 KiB       0  [emitted]        main
  extension.js.map  2.99 MiB       0  [emitted] [dev]  main
  Entrypoint main = extension.js extension.js.map
    [6] external "vscode" 42 bytes {0} [built]
    [8] ./src/consts.ts 5.75 KiB {0} [built]
   [11] ./src/config.ts 1.28 KiB {0} [built]
   [16] ./src/utils/index.ts 1.15 KiB {0} [built]
   [20] ./src/todo/items/item.ts 1.98 KiB {0} [built]
   [50] ./src/todo/document.ts 3.84 KiB {0} [built]
   [53] ./src/utils/folder.ts 2.21 KiB {0} [built]
   [66] ./src/views/embedded.ts 2.75 KiB {0} [built]
   [73] ./src/views/files.ts 2.88 KiB {0} [built]
   [87] ./src/utils/ast.ts 3.5 KiB {0} [built]
  [217] ./src/todo/decorators/document.ts 5.54 KiB {0} [built]
  [218] ./src/extension.ts 2.74 KiB {0} [built]
  [220] ./src/providers/completion.ts 1.4 KiB {0} [built]
  [737] ./src/providers/symbols.ts 1.82 KiB {0} [built]
  [745] ./src/todo/decorators/changes.ts 1010 bytes {0} [built]
      + 733 hidden modules
  ✨  Done in 10.03s.
  ```

**Comment by fabiospampinato** [comment]
> Wanted to contribute on issue labelled as help-wanted at a project I've been using daily for a year. I am sorry I don't understand if what I am doing is wrong? Did I break an etiquette rule, please let me know.

You're doing good, sorry my question was a bit abrupt, I just wanted to better understand what the benefits of this change would be in your opinion.

> If I recall correctly moment is not great with the tree shaking and is kinda chunky with bundle size. It's also stopped being developed and the maintainers themselves suggest alternatives (see here). Moment-mini is just zipped moment, not sure if it would be a better improvement.

`moment-mini` doesn't include a gazillion language packs, the minification doesn't matter because we are minifying the extension and its dependencies before shipping it to the marketplace anyway.

> I don't know how to benchmark startup time, can you point me how would I go with this?

There's the "Developer: Show running extensions" command in vscode that will tell you how long each extension took at startup.

> So the comparison below might not be very accurate.

Typescript and types don't get included in the output folder.

> du -h out
> 4.3M    out

That include source maps, source maps don't matter.

> My bad. I will fix "the daddy issues :D" if you think it's good idea to continue with this.

The different in size seems significant, about ~220kb if I'm reading this correctly.

I think we should probably go forward with this improvement, but I have a feeling switching to moment-mini instead would provide similarly good improvements with much fewer changes, are you interested in seeing what switching to `moment-mini` would look like instead?

**Comment by fabiospampinato** [comment]
Feel to submit another PR with moment-mini if you feel like it, IMHO that's probably the easier way to go, data-fns might be the better path forward long-term, but is also the riskier path.

**Comment by brkn** [comment]
Sorry for not being able to follow up on this, I will try to open another with moment-mini when I have time.

**Pull request closed without merging**
