### PR TITLE
Add `[lasted]`, `[wasted]` and `[elasped]` formattable tokens

### LINKED ISSUE #65: Add new statistics tokens: [lasted], [wasted] and [elapsed]
Hello,

I see that we have the token [est] that tells you the estimated time of a task, and this appears in todo.statistics.project.text. You could add a new token that is [last] that also tells you the total time the project lasted

### PR DESCRIPTION
**Pull request by jods4**
Fixes #65 

I tried to stick to the way things are done currently, using tricks to not impact the performance.

### CODE REVIEW

**Comment by jods4** [comment]
> Keep the coding style more consistent with mine

I tried 😉 
I will give a second look based on your comments but if you noticed stuff in the diff it would help to leave a quick comment.

>  don't like the magic numbers for char_*, this part of the code seems too low level

I did it this way because in issue you stressed that performance is critical. 
In fact, this new code path can be _much_ faster than previous code if there are many non-time tags in the document.

Doing a handful of int comparison (at worst: 5) is massively fast on CPU.

> use startsWithNumberRe.test ( tag ) instead of char_0/9, where startsWithNumberRe would be a regex that checks if the first character is a number.

There's no reason not to merge the `e` case, and it would be `/^@[e0-9]/`. 
That works the same but executing a regexp (even a simple one like above) is much slower than 1-3 int checks + it allocates memory.

If you want max perf the int checks are better. Does it matter? I don't know, I'm not familiar enough with the project; maybe not. You tell me.

> use .startsWith ( 'character' ) instead of char_character

It would be `.startsWith("@e")`.
It's not as bas as a regex but it's also slower than a single int equality.
It also means that the code contains more variations (regex vs startsWith), whereas the current code is consistent in its pattern.

Just let me know what you prefer.

> Rename tokens.ts to statistics_tokens.ts, and related changes

Will do

> formatTime looks ugly there, either put it inside the Time object or define it as a method of Tokens

I can make it a private method of tokens.
It just means a bunch of additional `this.` accessors in the getters.

> Setting all of Tokens's getters enumerable looks a bit weird,

It sure does. The nicest way to implement the caching without code and make things enumerable is to use a decorator
`@cached get all() { return this.pending + this.finished; }`
Since decorators are an experimental feature I wasn't sure if this was ok or not.

It's not because they're on the prototype that they're not enumerable: it's because they're getters (methods). Putting them on the object instance solves nothing + incurs the assignment of a field on each instance (they're a one-time thing on prototype).

Overall the `for (name of tokens)` felt bad to me and can easily iterate over stuff we'd like to hide.
If you're ok with changing the code in favor of `Tokens.supported: string[]` that seems much better to me and I'll do that.

**Comment by fabiospampinato** [comment]
> I tried 😉

And I appreciate it.

> I will give a second look based on your comments but if you noticed stuff in the diff it would help to leave a quick comment.

There are too many lines to mark, basically every if/else/else if you added and every getter (one line non-arrow functions). Update what you can, I'll do the rest.

> I did it this way because in issue you stressed that performance is critical.

Yes but we need to measure things before resolving to such low-level-looking code. Besides some of these checks can be skipped all together if we did what I proposed, which maybe would yield better performance than the current solution:

> - Make a function that checks if est/lasted/etc. are used in the following settings: (...)
> - If they are not, don't compute them at all
> - Be sure to refresh the result of this function when the configuration changes

> If you want max perf the int checks are better. Does it matter? I don't know, I'm not familiar enough with the project; maybe not. You tell me.

Keep it as it is, I'll do the measuring and update the code accordingly.

> Since decorators are an experimental feature I wasn't sure if this was ok or not.

It's ok.

> It's not because they're on the prototype that they're not enumerable: it's because they're getters (methods). Putting them on the object instance solves nothing + incurs the assignment of a field on each instance (they're a one-time thing on prototype).

I'm not so sure about that:

```ts
Object.keys ({ get bar () {} }) // => [ 'bar' ]
Object.keys ( new class { get bar () {} } ) // => []
```

> If you're ok with changing the code in favor of Tokens.supported: string[] that seems much better to me and I'll do that.

I'd prefer if you transformed the `Tokens` class into a plain object that looks like this:

```ts
const StatisticsTokens = {
  get/make/create () {
    return {
      tags: 0,
      ...
    };
  }
}
```

If you prefer I can do the changes myself, later in the day I'd like to merge this PR, just do what you can and I'll do the rest.

**Comment by jods4** [comment]
> if we did what I proposed, which maybe would yield better performance than the current solution

I agree but I didn't want to attempt major refactorings in this PR, so I sticked to the existing patterns.

> Yes but we need to measure things before resolving to such low-level-looking code.

It's not that low, it just checks a character (the first one after `@`). 😉 
About measuring:
- if you micro-benchmark this, the difference is massive;
- if you benchmark the whole program I am not sure but probably not as much since there's a _lot_ of _heavy_ work done elsewhere.

> I'm not so sure about that:

Beware: `Object.keys` only returns _own_ keys, not inherited ones. `for-in` includes inherited keys (the rendering code is based on for-in).

**Comment by jods4** [comment]
Done.
Feel free to tweak any remaining bit.

**Comment by rossgardt** [comment]
good work @jods4 ! thank you

**Comment by jods4** [comment]
> comparing code points isn't particularly high either IMHO.

There's no `char` type in JS, sadly :(
You may have noticed I'm comparing strings now instead. Doesn't make much difference perf-wise but code is shorter and clearer.

**Pull request merged**
