### PR TITLE
Adds customizable year, week, and day lengths. Closes #153.

### LINKED ISSUE #153: Support for man-days and man-weeks
The estimation of projects is not very useful in current form if I got 5d 15h what does it mean in real life? More like 3 man-weeks 1 man-day and 7 hours. 

It would be nice if project statistics would support md (man-day) and mw (man-weeks) with ability to set what man-day is (default 8h) and man-week (as 5*8h).

### PR DESCRIPTION
**Pull request by douglance**
I tried to follow the conventions of the repo, though it's a bit sloppy. 

At a high level, it would be nice to be able to specify the length of year/weeks/days in my config. I like to use Todo to estimate projects and 40h weeks / 8h days make a lot more sense to me; so I'd like to be able to use those lengths of time.

### CODE REVIEW

**Comment by douglance** [comment]
Also, sorry about the linting!

**Comment by fabiospampinato** [comment]
> Also, sorry about the linting!

No problem, make sure to fix it though, I can't just merge PRs which mess up the styling.

**Comment by douglance** [comment]
@fabiospampinato I fixed the linting and added default values.

**Comment by fabiospampinato** [comment]
I don't think this PR actually works, you're just changing how dates are _displayed_ under _some_ scenarios.

For instance I don't think this works when setting `"todo.timekeeping.elapsed.format": "long"`, nor it's changing anything about how [moment](https://github.com/fabiospampinato/vscode-todo-plus/blob/19090129233ee3deef761a2464d034ce5d5b3915/src/todo/items/todo.ts#L221-L223) computes dates, so things like `@lasted`, `@wasted`, `@done` and `@cancelled` will still work the same.

This is a tricky PR. Also I'm not sure if we should allow the length of things to be changed, perhaps we should introduce new units instead, e.g. "mw" (Man Week).

**Comment by douglance** [comment]
I will attempt to implement new units this weekend. Thanks @fabiospampinato

**Comment by fabiospampinato** [comment]
Closing as stale.

**Pull request closed without merging**
