### PR TITLE
Added option to customize project display template when project is completed 

### PR DESCRIPTION
**Pull request by hellos3b**
Issue #212

I thought it would be cool to display "lasted" time even when all items in a project were marked done.

I removed the `&& project.pending > 0` requirement for showing statistics, and added another property `todo.statistics.project.done` to create a secondary template. This defaults to "" so original functionality doesn't change

Setting it to "`[lasted]`" gets me the results I'm looking for

Screen Shot 2019-07-30 at 12 27 05 PM

I also added some type castings in `document.ts` and `time.ts` because typescript was getting angry and couldn't automatically infer it from the if statements, throwing errors

### CODE REVIEW

**Comment by fabiospampinato** [comment]
I don't quite like having multiple statistics templates as they will complicate the configuration. And should we add another one when no subtask has been completed? What about a project having a `@started` task? It would be better if you could just have a single template instead, so is having that `(10/10)` text displayed in completed projects really an issue?

**Comment by damianavila** [comment]
> so is having that (10/10) text displayed in completed projects really an issue?

I think the issue was that not about not showing the (10/10), the issue was not having the cumulative elapsed time. But I have found the following settings behaves as I pretended after the fix shipped with https://github.com/fabiospampinato/vscode-todo-plus/issues/214:

```json
    "todo.statistics.project.enabled": "global.projects < 100",
    "todo.statistics.project.text": "([pending]) [est] [lasted]"
```

image

**Comment by fabiospampinato** [comment]
> the issue was not having the cumulative elapsed time.

Yes but that turned out to be a non-issue since that is configurable already. Perhaps we should just always show project statistics by default?

**Comment by damianavila** [comment]
> Yes but that turned out to be a non-issue since that is configurable already

Yep, I agree.

>  Perhaps we should just always show project statistics by default?

I think that's probably a good idea.

**Comment by hellos3b** [comment]
Oh! When you said "check out this setting" I assumed it still required a PR. Setting it in settings.json works

Was fun though forking and figuring out how vscode extensions work

**Comment by fabiospampinato** [comment]
In v4.13.2 project-level statistics are always displayed by default 👍

**Pull request closed without merging**
