### PR TITLE
Added multi line toggle support

### PR DESCRIPTION
**Pull request by waseemx10**
I just added support for toggling multiple lines in a single selection.
multi-line-gif
P.S. It is my first ever pull request. Excuse me if I did anything wrong.

### CODE REVIEW

**Comment by codingdracula** [comment]
Looking forward to your revisions @waseemx10! I was actually looking for this feature today. I dislike having to use the multi cursor.

**Comment by waseemx10** [comment]
Hey @fabiospampinato,
Thanks for your feedback. I went with pure JavaScript as I didn't know about `lodash` until now (looks amazing). I have changed to using `_.flatten` and `_.range`.

I have also used `selection.start|end.line` as suggested. I didn't know that these properties existed in the `Selection` class (My mistake for not looking at the `Range` class extended by it).

Hopefully, that makes the code easier to read. I just found out about this extension yesterday. Fell in love with it instantly. 😄

@codingdracula , Thank you. Combining this with the existing multiple cursor toggling. You can do something like this:
Toggling Demo

**Comment by fabiospampinato** [comment]
@waseemx10 Perfect, thank you :) Now the code is much easier to read.

> I just found out about this extension yesterday. Fell in love with it instantly. 😄

What every developer would like to hear :)

I hope your first PR was overall a good experience for you.

**Comment by waseemx10** [comment]
Amazing. You're welcome, and thank you as well for including my contribution.

**Pull request merged**
